### PR TITLE
Add a camera platform for showing the map

### PR DESCRIPTION
**Pull request by huubvh95**
This pull request adds a camera integration to show the map. I could not extensively test this, because we are in the middle of a home renovation. The camera shows a black and white outline of the room in the first floormap. Related to #7. The camera view is inspired by this [integration](https://www.home-assistant.io/integrations/neato)

### CODE REVIEW

**Comment by BenjaminPaap** [comment]
Seems to work. Thank you for your work ❤️

**Comment by mitch65** [comment]
It's working. Love it. Thanks for tue work. 🙏🏼

**Comment by mikkelsiggaard** [comment]
Thank you!

**Comment by stubborneagle1984** [comment]
IMG_9697
IMG_9698

hi, 
Sorry, i have two question:
1) Is it correct that the current position of the robot is not shown? 
2) Also, is it correct that the status is always "inactive"?

thanks

**Pull request merged**
